-- 1. Create the expenses table if it doesn't exist
create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  date date not null,
  category text not null,
  amount numeric not null,
  description text not null
);

-- 2. Enable Row Level Security (RLS)
alter table public.expenses enable row level security;

-- 3. Create Policy: Allow users to view their own expenses
create policy "Users can view their own expenses"
  on public.expenses for select
  using (auth.uid() = user_id);

-- 4. Create Policy: Allow users to insert their own expenses
create policy "Users can insert their own expenses"
  on public.expenses for insert
  with check (auth.uid() = user_id);

-- 5. Create Policy: Allow users to update their own expenses
create policy "Users can update their own expenses"
  on public.expenses for update
  using (auth.uid() = user_id);

-- 6. Create Policy: Allow users to delete their own expenses
create policy "Users can delete their own expenses"
  on public.expenses for delete
  using (auth.uid() = user_id);

-- Instruction: Copy and paste this entire script into your Supabase SQL Editor and run it.
